application: gdatahealth
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- datastore_admin: on
  
handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /health/feeds/.*/files.*
  script: files.py
  secure: always

- url: /health/feeds/.*
  script: feeds.py
  secure: always

- url: /health/p.*
  script: profiles.py
  secure: always

- url: /health/ref.*
  script: ref.py
  secure: always

- url: /accounts.*
  script: accounts.py
  secure: always

- url: /admin
  script: admin.py
  secure: always
  login: admin
  
- url: .*
  script: main.py
  secure: always
