application: gdatahealth
version: 1
runtime: python
api_version: 1
  
handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /health/feeds/.*/files.*
  script: files.py

- url: /health/feeds/.*
  script: feeds.py

- url: /health/p.*
  script: profiles.py

- url: /admin
  script: admin.py

- url: /accounts.*
  script: accounts.py
  
- url: .*
  script: main.py
